/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package htw.berlin.wi.prog2;

import htw.berlin.wi.prog2.service.parsing.DummyInputParser;
import htw.berlin.wi.prog2.service.parsing.ExtendableInputParser;
import htw.berlin.wi.prog2.service.BurgerBuilder;
import htw.berlin.wi.prog2.ui.CommandLineUI;
import htw.berlin.wi.prog2.ui.UserInputWrapper;

public class BurgerBotApp {
    public static void main(String[] args) {
        ExtendableInputParser parser = new DummyInputParser();
        BurgerBuilder builder = new BurgerBuilder(BurgerBuilder.CreationStyle.PRECOMPUTED);
        CommandLineUI clui = new CommandLineUI(new UserInputWrapper(System.in, System.out), builder, parser);
        clui.launch();
    }
}
